### ISSUE TITLE
Mako stops showing notification.

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#226]
It doesn't stop running. It just doesn't show anything. It works normally for a moment before it stops appearing. I can get it to show again by using `makoctl reload`.

**Comment by YerinAlexey** [comment]
For me even `makoctl reload` doesn't help

**Comment by dedguy21** [comment]
I too am having this issue with mako

**Comment by ifreund** [comment]
Can anyone still reproduce this? I seem to be unable to. If so, how long does mako need to run for before this happens?

**Comment by Leon-Plickat** [comment]
I can

**Comment by ifreund** [comment]
hmm, well a `WAYLAND_DEBUG=1` log of this happening would probably go a long way towards diagnosing this issue.

**Comment by snakedye** [comment]
WAYLAND_DEBUG=1 doesn't show anything special, at some point it just stops doing anything when you send notifications.

I noticed it consistently happens when my PC comes back from sleep.

**Comment by ifreund** [comment]
> WAYLAND_DEBUG=1 doesn't show anything special, at some point it just stops doing anything when you send notifications.

If you have a log available I would very much like to see it even if you don't notice anything "special". I still can't reproduce this myself, even with sleeping, removing/re-adding outputs, waiting for hours, etc.

**Comment by ifreund** [comment]
So I mentioned this issue to the mako developers and they pointed me to https://github.com/emersion/mako/issues/281 as a possible cause which has been fixed in the latest mako release. Is everyone here using mako 1.5 or later?

**Comment by snakedye** [comment]
I tried with mako upstream mako and I still experience this. I'll try later with sway.

[mako.log](https://github.com/ifreund/river/files/6631781/mako.log)

**Comment by shiorid** [comment]
I'm running mako 1.5 and the bug still goes on River.
There is no problem at all with Sway and Hikari (FreeBSD focused compositor).
I'll try to catch what is going on with DTrace, since the logs are not that helpful.

**Comment by elshize** [comment]
Here's another log file; I experience this with mako 1.5-1. I haven't noticed this problem on Sway previously.

[mako.log](https://github.com/ifreund/river/files/6681131/mako.log)

**Comment by ifreund** [comment]
Hey, I've still been unable to reproduce this myself but I think this patch might resolve the issue. If anyone has a chance to try it and confirm/deny that would be very useful. https://github.com/ifreund/river/tree/try-fix-mako

**Comment by elshize** [comment]
Thanks @ifreund I'm running it now, I'll report back with my findings. However, I notice a weird thing: now my `wofi` doesn't open in the middle of the screen as it used to. Screenshot of both my screens below. But I'm not sure if that's related to this change or maybe some other change done after last time I compiled. Once I investigate the mako fix, I'll compile master and see if it happens on it as well.

![2021-06-19T17:18:08,174034090-04:00](https://user-images.githubusercontent.com/3026120/122655716-9727e700-d122-11eb-8732-491ba8c0f65c.png)

**Comment by elshize** [comment]
Sadly it doesn't seem to work. mako still stopped working after a while (I noticed it after about an hour from starting river, can't say exactly when it happened).

**Comment by elshize** [comment]
btw wofi works as expected on `master` build.

**Comment by ifreund** [comment]
@elshize thanks for giving it a try, I think I found the real problem and I think this patch should fix things if you (or anyone else) would be willing to test. 
```diff
From 6cf7ceceb6d6adb336461492c8eaa5997dc7922b Mon Sep 17 00:00:00 2001
From: Isaac Freund <ifreund@ifreund.xyz>
Date: Sun, 20 Jun 2021 12:33:02 +0200
Subject: [PATCH] layer-shell: maybe fix mako take two?

---
 river/LayerSurface.zig | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/river/LayerSurface.zig b/river/LayerSurface.zig
index 3031cee..6fd8fd5 100644
--- a/river/LayerSurface.zig
+++ b/river/LayerSurface.zig
@@ -60,7 +60,9 @@ pub fn init(self: *Self, output: *Output, wlr_layer_surface: *wlr.LayerSurfaceV1
     const node = @fieldParentPtr(std.TailQueue(Self).Node, "data", self);
     const list = &output.layers[@intCast(usize, @enumToInt(self.state.layer))];
     list.append(node);
+    wlr_layer_surface.current = wlr_layer_surface.client_pending;
     output.arrangeLayers();
+    wlr_layer_surface.current = self.state;
     list.remove(node);
 
     // Set up listeners that are active for the entire lifetime of the layer surface
-- 
2.32.0
```

**Comment by elshize** [comment]
@ifreund Trying it out now.

**Comment by shiorid** [comment]
Hey, the patch works perfectly on FreeBSD. Mako is running flawlessly!

**Comment by ifreund** [comment]
> Hey, the patch works perfectly on FreeBSD. Mako is running flawlessly!

@shiorid just to confirm, you mean that the patch in this comment seems to have fixed things? https://github.com/ifreund/river/issues/226#issuecomment-864533429

I've found what seems to be the root cause of the issue in a TODO in mako's source and don't see why that patch should fix it:
https://github.com/emersion/mako/blob/445bf2d28d162007507580c40c9265978736f148/wayland.c#L563-L565

I believe the proper fix is #336, but I was never able to reproduce this race condition so I am unable to confirm myself, if anyone here could test #336 that would be much appreciated.

**Comment by shiorid** [comment]
@ifreund Yes, I'm referring to [this](https://github.com/ifreund/river/issues/226#issuecomment-864533429) patch. After recompiling, the problem stopped to show up.
I'd like to state that FreeBSD ports apply some patches to Zig, River and wlroots, and I'm not a Zig guy myself.

I'll try to reproduce the problem and test #336 in a more _common_ and clean environment, so I won't misguide you.
