### ISSUE TITLE
No damage on opacity change

### ISSUE THREAD

**Issue by snakedye** [ifreund/river#299]
Spawned windows keep their initial opacity. 

https://user-images.githubusercontent.com/49378990/120125181-9f28e280-c185-11eb-9dbc-d3eb11fac95d.mp4

**Comment by ifreund** [comment]
Should be fixed by 9ee788b65e5b6616a13d5c34eb9e58833144e511.

**Comment by snakedye** [comment]
I doesn't fix it. It's weird, when I'm recording my screen, it behaves properly, when I don't it directly goes from the initial transparency to the final instead of incrementing.

**Comment by ifreund** [comment]
acaf19246595f4b300207d146f727c204ac63dae should actually fix it, I was sleepy.

**Comment by snakedye** [comment]
Now it's fine
