### ISSUE TITLE
wleird/unmap causes improper window sizing

### ISSUE THREAD

**Issue by lazy-dolphin** [ifreund/river#31]
Can be reproduced by command `alacritty -e exit`.
![20200524_17h38m35s_grim](https://user-images.githubusercontent.com/51233180/82753773-e697c880-9de5-11ea-98a6-13cb55f73f41.png)

**Comment by Ordoviz** [comment]
The same happens to my terminals when I run `echo | wl-copy` or `wl-paste`. You can refresh the terminals be changing master-factor, killing a terminal, or opening another terminal.

Damaged programs not getting refreshed is currently the main issue I experience with river. When gpg-agent prompts me to type my password, no bullets appear as I am typing. This can be fixed by toggling its floating behavior. Sometimes I need to manually refresh Firefox after every key press. Only killing Firefox fixes it.

**Comment by ifreund** [comment]
I believe I've fixed this in c0d7e71ec499d3e520c5567f4fbf6c6bda723adc. The code handling atomic layout updates is quite delicate, so any testing would be appreciated.

Note that `wl-copy` and `wl-paste` may cause a slight flicker as they are currently using a hack that involves creating and instantly destroying a surface. There is a protocol I plan on implementing soon that will avoid the need for this hack though (wlr-data-control).

**Comment by lazy-dolphin** [comment]
@ifreund : Issue still persists but is less severe. I think `alacritty` loads slow enough to avoid this problem but it still occurs in fast-to-load clients such as [`foot`](https://codeberg.org/dnkl/foot) (amazing terminal emulator btw). Everytime I run `footclient exit` in foot, it alternates between normal behavior and the situation in the image.
![20200609_08h15m02s_grim](https://user-images.githubusercontent.com/51233180/84100911-75cdee80-aa2a-11ea-903b-7093cd888c54.png)

**Comment by ifreund** [comment]
I've been unable to reproduce this with anything except `foot` running in client/server mode. It also only happens when using `footclient exit`; other programs that spawn and instantly close do not trigger it even while running 3 `footclient` terminals. I'm starting to suspect that this is a bug with foot's client/server mode.

**Comment by ifreund** [comment]
This is definitely a bug with `foot` as only `footclient` instances are affected, other programs are fine.

**Comment by lazy-dolphin** [comment]
@ifreund I have been able to reproduce this using emersion's compositor testing utilities ([wleird-unmap](https://github.com/emersion/wleird/blob/master/unmap.c)). Here's what I did:
* changed `1000` in `unmap.c` to a small number(`20` in my case) and then compiled it.
* opened `firefox` and `alacritty` on a fresh tag.
* ran `unmap` executable through `alacritty`.
And the same thing happens with firefox.

**Comment by ifreund** [comment]
Just did some more poking at this and I've confirmed that river is indeed failing to send a new configure to some clients in these cases. As far as I can tell, this is caused by a race in wlroots which I'm currently looking into fixing. If I use the wlroots api to request that a new size be sent to the client between the ack of the last configure and the first commit of that client's surface after said ack, no new configure is sent.

Hopefully this is in fact the bug, sorry for pointing fingers at foot :)

**Comment by ifreund** [comment]
This should be fixed by the patch here: https://github.com/swaywm/wlroots/pull/2342. Any testing would of course be appreciated as this code is rather delicate.

**Comment by dnkl** [comment]
> Hopefully this is in fact the bug, sorry for pointing fingers at foot :)

No worries. I didn't even know about it, since no one came screaming over at the foot issue tracker :)

If work allows it, I'll try to test the wlroots patch later today.

**Comment by dnkl** [comment]
Your branch is a couple of commits behind master. Specifically, the 0.11 
version bump, which also included a so-version bump.

I rebased your branch against master, and installed a release build. With 
this, starting either Firefox, Alacritty, foot, or footclient causes both 
Sway and river to crash.

Layer-surface based applications work though.

I have not debugged this, but if needed I can do debug builds and provide 
stack traces.

**Comment by dnkl** [comment]
For what it's worth, I cannot reproduce the resizing issue on Sway (with 
an unpatched wlroots).

**Comment by ifreund** [comment]
Thanks for testing it out and for the reminder to rebase!

> With this, starting either Firefox, Alacritty, foot, or footclient causes both
Sway and river to crash.

Hmm, that not good. Unfortunately I can't reproduce this in river or sway. I'll do some more poking around, but a stack trace would likely help a lot if you have a minute. 

> For what it's worth, I cannot reproduce the resizing issue on Sway (with
an unpatched wlroots).

This is expected, I took a slightly different path from sway with how I handle atomic layout updates. Sway has a queue of transactions and applies each in series while river allows for preemption. If a new transaction interrupts a currently pending one the new state is "merged" into the pending state to insure that no intermediate frames are shown between transactions. (A "transaction" here is a set of configure events sent to multiple clients for which an ack from each client is required before drawing the next frame.) All this means is that the way sway handles configures side-steps this race.

**Comment by dnkl** [comment]
PEBCAK; I assumed the patch was ABI compatible, but I guess not. 
Recompiling river against the patched wlroots works as expected; no 
crashes and no resizing issues. Sorry about the noise!

Thanks for the explanation regarding atomic updates. Really hope that 
works out well.

**Comment by ifreund** [comment]
> PEBCAK; I assumed the patch was ABI compatible, but I guess not.
Recompiling river against the patched wlroots works as expected; no
crashes and no resizing issues. Sorry about the noise!

Yep, that would do it. No worries!

> Thanks for the explanation regarding atomic updates. Really hope that
works out well.

I'm pretty happy with the solution so far. The disadvantage of this approach
is that it does not play very well with interactive resizing of multiple views at
once. However, this is not something I currently plan to implement in river.
(Interactive resize of floating views is planned.)

**Comment by ifreund** [comment]
wlroots 0.12.0 has the patch that fixed this issue
